wcs_coav_planetmodel:
    resource: "@WCSCoavBundle/Resources/config/routing/planetmodel.yml"
    prefix:   /planetmodel

wcs_coav_homepage:
    path:     /
    defaults: { _controller: WCSCoavBundle:Default:index }

wcs_coav_flight:
    resource: "@WCSCoavBundle/Resources/config/routing/flight.yml"
    prefix:   /flight

wcs_coav_reservation:
    resource: "@WCSCoavBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

wcs_coav_terrain:
        resource: "@WCSCoavBundle/Resources/config/routing/terrain.yml"
        prefix:   /terrain



