services:
#    wcs_coav.example:
#        class: WCS\CoavBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    app.admin.terrain:
        class: WCS\CoavBundle\Admin\TerrainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Fly", label: "Terrain" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Terrain
            - ~


    app.admin.flight:
        class: WCS\CoavBundle\Admin\FlightAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Fly", label: "Flight" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Flight
            - ~

    app.admin.planeModel:
        class: WCS\CoavBundle\Admin\PlaneModelAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Fly", label: "PlaneModel" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\PlanetModel
            - ~

    app.admin.user:
        class: WCS\CoavBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Reservation", label: "User" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\User
            - ~

    app.admin.reservation:
        class: WCS\CoavBundle\Admin\ReservationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Espace Reservation", label: "Reservation" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Reservation
            - ~