WCS\CoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        pilot:
            type: string
            length: 255
        freeSeats:
            type: integer
            nullable: true
        takeofTime:
            type: datetime
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: departures
            joinColumn:
                name: departure_id
                referencedColumnName: id
        arrival:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: arrivals
            joinColumn:
                name: arrival_id
                referencedColumnName: id
        plane:
            targetEntity: WCS\CoavBundle\Entity\PlanetModel
            inversedBy: planes
            joinColumn:
                name: plane_id
                referencedColumnName: id

    oneToMany:
        flights:
            targetEntity: Reservation
            mappedBy: flight