# src/WCS/CoavBundle/Resources/config/doctrine/User.orm.yml

WCS\CoavBundle\Entity\User:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: { }

    manyToMany:
        reservation:
            targetEntity: WCS\CoavBundle\Entity\Reservation
            inversedBy: passengers