<?php

namespace WCS\CoavBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlanetModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetModelRepository extends EntityRepository
{
}
